<a href="https://colab.research.google.com/github/BobTheConstructor/Estudos/blob/main/PyDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instalando o faker, Gerador de codigo ficticios

In [ ]:
# instalação do faker (necessario para que funcione)
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.11/dist-packages (37.3.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.2)

importação das bibliotecas

In [ ]:
#bibliotecas Python para dados
import pandas as pd # utilizada para a criação do DataFrame
import numpy as np
import matplotlib.pyplot as plt # utilizada para a criação de graficos

#bibliotecas para criação da tabela
import random # escolhas aleatorias entre opções
from faker import Faker # criação de nomes, cpf, cnpj falsos
from datetime import datetime, timedelta # para implementção de datas

A criação de dados foi feita com base em vendas por 3 anos.

In [ ]:
fake = Faker('pt_BR')
Faker.seed(123)
random.seed(123)

ponto =([
    7,10,6,3,1,3,7,4,3,6
])

explicacao = ([
    'entre "sim" e "não" se é ou não uma empresa (usado para filtragem)',
    'o nome da empresa ou cliente',
    'cpf em caso de "empresa" sim e cpnj no caso não',
    'a data da compra',
    'o tamanho do veiculo medio(carros), grande(caminhões)',
    'a medida do pneu',
    'se o pneu é uma restauração de um pneu usado',
    'a quantidade de pneus comprados',
    'o valor de cada pneu individual comprado',
    'o valor total da(s) venda(s) do(s) pneu(s)'
])

# Função para gerar medida do pneu
def gerar_medida(veiculo):
    if veiculo == 'medio':
        largura = random.choice([165, 175, 185, 195])
        altura = random.choice([65, 75])
        aro = random.choice([13, 14, 15, 16])
    else:  # caminhão
        largura = random.choice([205, 215, 225])
        altura = random.choice([45, 55, 60, 65, 70])
        aro = random.choice([15, 16, 17])
    return f"{largura}/{altura}.{aro}"

cnpj_nome = {}
for _ in range(10):
    cnpj = fake.cnpj()
    nome = fake.company()
    cnpj_nome[cnpj] = nome

# Geração dos dados
dados = []
for _ in range(800):
    empresa = random.choice(['Sim', 'Não'])
    if empresa == 'Sim':
      cpf_cnpj = random.choice(list(cnpj_nome.keys()))
      nome_empresa = cnpj_nome[cnpj]
    else:
      cpf_cnpj = fake.cpf()
      nome_empresa = fake.name()
    data_compra = fake.date_between(start_date='-3y', end_date='today')
    veiculo_porte = random.choice(['medio', 'grande'])
    medida_pneu = gerar_medida(veiculo_porte)
    remode = random.choice(['Sim', 'Não'])
    quantidade = random.randint(1, 6)

    if remode == 'Sim':
        valor_unitario = round(random.uniform(150.00, 190.00), 2)
    else:
        valor_unitario = round(random.uniform(200.00, 250.00), 2)

    valor_total = round(quantidade * valor_unitario, 2)

    dados.append([
        empresa,
        nome_empresa,
        cpf_cnpj,
        data_compra,
        veiculo_porte,
        medida_pneu,
        remode,
        quantidade,
        valor_unitario,
        valor_total
    ])

# Criar DataFrame
colunas = [
    'empresa',
    'Nome',
    'cpf_cnpj',
    'data_compra',
    'veiculo_porte',
    'medida_pneu',
    'Remolde',
    'Qnt_vendas',
    'Vr_unitario',
    'Vr_Total'
]



tabela = pd.DataFrame(dados, columns=colunas)

# Corrigindo a data para dd/mm/yyyy
tabela['data_compra'] = pd.to_datetime(tabela['data_compra']).dt.strftime('%d/%m/%Y')

Exportando a tabela

In [ ]:
tabela.to_csv('dados_vendas.csv', index=False)

Importação da tabela

In [ ]:
dados = pd.read_csv('dados_vendas.csv')

Codigo para explicação das colunas

In [ ]:
for i in range(10):
  print('-'*100)
  print(f'| {colunas[i]} '+'-'*ponto[i] +f'> {explicacao[i]} ')
print('-'*100)

----------------------------------------------------------------------------------------------------
| empresa -------> entre "sim" e "não" se é ou não uma empresa (basicamente usado para filtragem)
----------------------------------------------------------------------------------------------------
| Nome ----------> o nome da empresa ou cliente
----------------------------------------------------------------------------------------------------
| cpf_cnpj ------> cpf em caso de "empresa" sim e cpnj no caso não
----------------------------------------------------------------------------------------------------
| data_compra ---> a data da compra
----------------------------------------------------------------------------------------------------
| veiculo_porte -> o tamanho do veiculo medio(carros), grande(caminhões)
----------------------------------------------------------------------------------------------------
| medida_pneu ---> a medida do pneu
----------------------------------------------------------------------------------------------------
| Remolde -------> se o pneu é uma restauração de um pneu usado
----------------------------------------------------------------------------------------------------
| Qnt_vendas ----> a quantidade de pneus comprados
----------------------------------------------------------------------------------------------------
| Vr_unitario ---> o valor de cada pneu individual comprado
----------------------------------------------------------------------------------------------------
| Vr_Total ------> o valor total da(s) venda(s) do(s) pneu(s)
----------------------------------------------------------------------------------------------------

Um pequeno teste para se ter uma noção se a tabela corresponde as espectativas

In [ ]:
tabela.head(10)

,empresa,Nome,cpf_cnpj,data_compra,veiculo_porte,medida_pneu,Remolde,Qnt_vendas,Vr_unitario,Vr_Total
0,Sim,Aparecida,97.430.286/0001-87,16/06/2022,medio,195/75.13,Sim,4,171.45,685.80
1,Não,Cauê Pinto,730.265.841-26,12/08/2022,grande,205/55.15,Não,5,216.69,1083.45
2,Sim,Aparecida,32.097.465/0001-07,29/06/2023,medio,195/65.16,Sim,1,162.62,162.62
3,Não,Lorenzo da Luz,196.043.728-31,17/04/2025,medio,165/65.14,Sim,1,161.67,161.67
4,Não,Dra. Cecília Freitas,085.329.164-06,06/06/2024,grande,215/65.15,Não,3,226.08,678.24
5,Não,Vitor Fernandes,106.429.573-80,23/12/2023,medio,185/65.16,Não,6,226.93,1361.58
6,Não,Dr. Rael da Rosa,268.051.397-59,18/09/2023,grande,215/70.15,Sim,6,182.81,1096.86
7,Não,Maria Eduarda Câmara,025.647.139-80,08/02/2025,grande,205/60.16,Não,1,236.16,236.16
8,Não,Theodoro Barros,514.789.263-09,17/04/2025,grande,205/55.17,Sim,6,164.54,987.24
9,Não,Luigi Novaes,830.124.679-04,15/01/2024,medio,195/65.15,Não,6,236.01,1416.06

Amostragem da DataBase do DataFrame

In [ ]:
lin, col = tabela.shape
print(f"O DataFrame tem {lin} linhas e {col} colunas.")

O DataFrame tem 800 linhas e 10 colunas.

Media do total de vendas

In [ ]:
md = tabela['Vr_Total'].mean(axis=0).round(2)
mdVendas = tabela['Qnt_vendas'].mean(axis=0)
print(f'A media de vendas totais é: {md}, tendo em vista que cada cliente compra: {mdVendas} Pneus em media')

A media de vendas totais é: 669.76, tendo em vista que cada cliente compra: 3.3925 Pneus em media

A maior compra de cada cnpj filtradas da maior para a menor

In [ ]:
tabela.loc[tabela[tabela['empresa'] == 'Sim'].groupby('cpf_cnpj')['Vr_Total'].idxmax()].sort_values(by="Vr_Total", ascending=False)

,empresa,Nome,cpf_cnpj,data_compra,veiculo_porte,medida_pneu,Remolde,Qnt_vendas,Vr_unitario,Vr_Total
314,Sim,Aparecida,71.095.846/0001-09,11/10/2024,grande,215/60.16,Não,6,246.16,1476.96
303,Sim,Aparecida,85.960.143/0001-06,24/01/2024,grande,205/45.15,Não,6,245.75,1474.50
260,Sim,Aparecida,73.916.485/0001-31,04/07/2024,grande,225/70.15,Não,6,239.58,1437.48
79,Sim,Aparecida,98.503.472/0001-61,20/05/2024,grande,215/55.17,Não,6,238.43,1430.58
95,Sim,Aparecida,65.098.174/0001-84,10/04/2024,medio,195/65.15,Não,6,231.63,1389.78
114,Sim,Aparecida,59.608.342/0001-31,10/11/2024,medio,175/65.15,Não,6,230.58,1383.48
367,Sim,Aparecida,97.430.286/0001-87,03/10/2022,grande,225/45.16,Não,6,228.98,1373.88
218,Sim,Aparecida,32.097.465/0001-07,09/02/2023,grande,205/65.17,Não,6,225.64,1353.84
69,Sim,Aparecida,31.502.897/0001-85,15/01/2024,medio,165/65.13,Não,6,212.31,1273.86
214,Sim,Aparecida,04.163.295/0001-78,19/11/2024,medio,195/75.14,Sim,6,172.54,1035.24

Tabela com as 10 maiores compras de pessoas fisicas

In [ ]:
tabela.loc[tabela[tabela['Empresa'] == 'Não'].groupby('cpf_cnpj')['Vr_Total'].idxmax()].sort_values(by="Vr_Total", ascending=False).head(10)

,Empresa,cpf_cnpj,data_compra,veiculo,medida_pneu,Remolde,Qnt_vendas,Vr_unitario,Vr_Total
151,Não,723.598.601-86,23/05/2025,caminhao,215/70.17,Não,6,243.89,1463.34
70,Não,452.730.689-83,26/09/2024,carro,185/75.16,Não,6,237.01,1422.06
9,Não,581.974.360-10,19/11/2024,carro,195/65.15,Não,6,236.01,1416.06
113,Não,716.024.395-16,01/12/2023,caminhao,215/70.17,Não,6,232.62,1395.72
122,Não,783.621.495-82,24/12/2024,caminhao,215/55.16,Não,6,232.44,1394.64
102,Não,765.093.428-47,13/05/2025,carro,195/75.16,Não,6,230.05,1380.30
5,Não,196.043.728-31,18/06/2023,carro,185/65.16,Não,6,226.93,1361.58
182,Não,758.193.420-97,23/06/2024,carro,195/75.14,Não,6,224.66,1347.96
48,Não,360.718.924-22,03/09/2023,carro,165/65.15,Não,6,220.04,1320.24
171,Não,512.987.306-86,31/07/2024,caminhao,215/45.15,Não,6,219.60,1317.60